### ISSUE TITLE
client: full list of windows is not shown at bottom

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#114]
When switching windows, only active window is shown below, i.e. it alternates between

`[my time] [my nick] [0:console] []` and
`[my time] [my nick] [1:someone] []`.

I think it should be `[my time] [my nick] [0:console] [1:someone]` at all times, with active window shown in bold.

**Comment by marcopeereboom** [comment]
This will need some sort of wrapping on the status line and make it inherently hard to read.

Use ```/list c``` to obtain this information.
