### ISSUE TITLE
client: explicitly respond about empty lists

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#118]
Explicitly respond about empty lists: `/list invites` -> `There are no pending invites` instead of `Pending invites:` followed by nothing. This is good recent UX practice.

**Comment by marcopeereboom** [comment]
This is a surprisingly hard problem to solve because not all lists live in memory. In certain cases, you'd have to walk the lists twice to see if there is anything to print or not. In addition, I don't feel that adding an explicit 0 case helps to convey the message better.
