### ISSUE TITLE
log: don't print timestamp twice

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#120]
In the log file, startup message and help command responses print timestamp twice: first the a short timestamp followed by the duplicate long timestamp. This eats lots of time.

```
17:30:05 [INF] Start of day
17:30:05 [LOG] 2018-06-28 17:30:05 Welcome to Zero Knowledge Communications!
17:30:05 [LOG] 2018-06-28 17:30:05 
17:30:05 [LOG] 2018-06-28 17:30:05 Your fingerprint is: ...
```

Either print them once, or explain why it's shown twice (e.g. perhaps both server and client time is shown for each line ?).

**Comment by marcopeereboom** [comment]
This is working as designed so that you can see the difference between server and client timestamps.
