### ISSUE TITLE
poor UX and visual feedback during first /q attempts

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#122]
After I connected the server for the first time, I tried /q someone and nothing happened. I tried a few more times and nothing. Then I did /info someone and got "nick not found". An hour later the chat started but I didn't understand who started it or how it happened. Then I checked zkclient.log:

```
17:30:xx [LOG] xxxx-xx-xx 17:30:xx Welcome to Zero Knowledge Communications!
17:30:xx [LOG] xxxx-xx-xx 17:30:xx <welcome message>
17:33:xx [LOG] initiating kx with <identity1>
17:33:xx [LOG] [InitiateKX]: nk = ...
17:33:xx [LOG] [InitiateKX]: nc = ...
17:33:xx [LOG] ok
17:33:xx [LOG] xxxx-xx-xx 17:33:xx invalid command, usage: /q <nick>
17:35:xx [LOG] initiating kx with <identity1>
17:35:xx [LOG] [InitiateKX]: nk = ...
17:35:xx [LOG] [InitiateKX]: nc = ...
17:35:xx [LOG] could not save identity: identity already exists
17:46:xx [LOG] initiating kx with <identity1>
17:46:xx [LOG] [InitiateKX]: nk = ...
17:46:xx [LOG] [InitiateKX]: nc = ...
17:46:xx [LOG] could not save identity: identity already exists
17:47:xx (I try to /q <nick1>)
17:47:xx [LOG] xxxx-xx-xx 17:47:xx nick not found: <nick1>
18:10:xx [LOG] initiating kx with <identity1>
18:10:xx [LOG] [InitiateKX]: nk = ...
18:10:xx [LOG] [InitiateKX]: nc = ...
18:10:xx [LOG] could not save identity: identity already exists
18:37:xx [LOG] xxxx-xx-xx 18:37:xx Client to Client Key Exchange complete:
18:37:xx [LOG] xxxx-xx-xx 18:37:xx Identity   : <identity1>
18:37:xx [LOG] xxxx-xx-xx 18:37:xx Fingerprint: <fingerprint1>
18:37:xx [LOG] xxxx-xx-xx 18:37:xx Name       : <name1>
18:37:xx [LOG] xxxx-xx-xx 18:37:xx Nick       : <nick1>
18:37:xx [LOG] xxxx-xx-xx 18:37:xx conversation started [1]: <nick1> <fingerprint1>
```

I _guess_ every "initiating kx" corresponds to me trying to /q <nick1> but I'm not sure. Something is not right in this log and UI. If the kx is started and pending, on subsequent attempts to "/q <nick>" the UI should respond with "kx with <id> in progress, please wait" and not start a new kx. Else, if every but the last kx failed, it should say "kx failed" to let user know he shall retry and why.

In any case:

* after I "/q <nick>" the "initiating something" must show both on the UI and in the log (not only in the log),
  * currently there is no visual feedback when some long running process has started
* explain to the user that kx is automated but can take some time (e.g. both users must meet online a few times?)

**Comment by marcopeereboom** [comment]
I fixed a bunch of this weirdness in #100. Please revaluate this issue after testing with that version.
