### ISSUE TITLE
README references config file, and zkclient starts with defaults when missing

### ISSUE THREAD

**Issue by chappjc** [companyzero/zkc#131]
https://github.com/companyzero/zkc/blob/801968c7e27541ef4b4e4da0e766810de3ac6cb5/zkclient/settings.go#L163-L164

Two related issues:
1. There is no longer a zkclient.conf file, so [the README](https://github.com/companyzero/zkc/blob/master/README.md#zkclient) is no longer accurate.
2. The only way to create the config file, short of copying zkclient.conf.go to zkclient.conf and removing the wrapping code, is to start zkclient with no config file.  However, after writing out the config file with defaults, zkclient starts up (instead of quitting so you can edit the config file).  Thus, there is no way to create the config file with defaults without actually starting up with default, which is not always desirable.

**Comment by marcopeereboom** [comment]
That is fair. I'll add a switch to export the config file but it won't be in the 0.3.0 release.
