### ISSUE TITLE
"day changed" message appears before every single new message after the new day after switching to room

### ISSUE THREAD

**Issue by jrick** [companyzero/zkc#135]
When a room is not in focus, and new messages are received in it overnight, once the room is switched to, the "day changed" messages appear before every message since the new day in the room.  It should only appear once before the first new message of the day.

**Comment by jrick** [comment]
These messages also appear in the logs.

**Comment by jrick** [comment]
The messages seem to continue to occur even after the window is focused, and only stop once you post a message to the room.

**Comment by marcopeereboom** [comment]
This was fixed
