### ISSUE TITLE
Signing and other security considerations

### ISSUE THREAD

**Issue by Tsutsukakushi** [companyzero/zkc#27]
If the focus really is security then it seems odd that the releases aren't signed. It would make sense to [sign the commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) as well.

The "go get" is a bad way to install security software since you place blind trust on GitHub. You probably couldn't use "go get" with signed releases anyways since it seems to lack any sort of signature verification mechanisms.

Additionally the decred.com site is using decred.org signature, this will warn users about a bad signature and open them up to a man-in-the-middle attack in case they accept it without checking it.

Writing secure software won't be much use if you can't deliver it in a secure manner.

**Comment by dajohi** [comment]
Signing tags is now implemented starting with v0.3.0
