### ISSUE TITLE
I'd strongly prefer for all errors to go to window 0

### ISSUE THREAD

**Issue by jrick** [companyzero/zkc#29]
Have some messed up ratchets after rebooting and currently all send errors to people in group chats that have not yet kx'd with me (one for each person) are printed to the open window.  I would prefer these to go to window 0 so it doesn't just flood the group chat with errors.

**Comment by dajohi** [comment]
Perhaps make the '0' on the status bar red too, to indicate there is an unread error.

**Comment by jcvernaleo** [comment]
I'm very in favor of this.

**Comment by marcopeereboom** [comment]
While I understand the urge for this do realise that there is no feedback to a user typing.  You have to switch back to console 0 to see if anything went wrong.  No one will ever do that and go on their merry way without seeing the errors.

**Comment by jrick** [comment]
I like dhill's suggestion for highlighting window 0 in red so users know there are new errors displayed there.

Also I just learned that these errors are also added to the chat logs.  Would really like it to not do that.

**Comment by marcopeereboom** [comment]
I added a FloodfT (#100) print that prints to the console and to the user window if it is open; it will print to the current window if it isnt open. I have been sprinkling this over the code as I ran across errors and will continue to do so. Please create new issues for specific errors that should be printed like this.
