### ISSUE TITLE
zkc freeze with certain text

### ISSUE THREAD

**Issue by dajohi** [companyzero/zkc#33]
paste this into zkc, hit enter, freeze.

```-4: failed to fetch address '�3���wy2��y��/PK��': address not found```

**Comment by marcopeereboom** [comment]
So I remember this and then it went away when I used a different/newer terminal.  Is it back or are you using something funky?

**Comment by jcvernaleo** [comment]
I hit it also (with a mangled decred address just like dhill) using a gnome terminal and tmux so pretty standard stuff.

**Comment by martelletto** [comment]
The issue seems to be caused by termbox-go. termbox-go's editbox.go demo exhibits the same behaviour. Please let me know if I should investigate this issue further.
