### ISSUE TITLE
CTRL-U behavior

### ISSUE THREAD

**Issue by raedah** [companyzero/zkc#51]
I am not a fan of how CTRL-D and CTRL-U act like pageup and pagedown. CTRL-U should have the standard unix behavior of deleting the current line.

**Comment by jcvernaleo** [comment]
I really don't want the ctrl-u/d behavior changed.  I have some keyboards that lack pg-up and pg-down so zkc would be pretty much unusable without the current behavior.

**Comment by raedah** [comment]
Could make it a config option for those who have odd keyboards.
http://web.cecs.pdx.edu/~rootd/catdoc/guide/TheGuide_38.html

**Comment by marcopeereboom** [comment]
Clearly you people don't use vi!  Vi is also obviously correct and emacs is wrong :)

I am going to close this because this is simply preference.  If you want this behavior we need to add keybindings.
