### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by raedah** [companyzero/zkc#83]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75c397]

goroutine 13 [running]:
github.com/companyzero/zkc/sigma.(*SigmaKX).Write(0x0, 0xc420474028, 0x14, 0x40, 0x0, 0x0)
        /home/dhill/.go/src/github.com/companyzero/zkc/sigma/sigma.go:315 +0x37
main.(*ZKC).writeMessage(0xc4201121c0, 0xc4202c2008, 0x80c060, 0xaf1688, 0x0, 0x0)
        /home/dhill/.go/src/github.com/companyzero/zkc/zkclient/zkclient.go:1404 +0x1ed
main.(*ZKC).scheduler.func4(0xc4201121c0, 0xc420013a58, 0xc4200faca0, 0xc4200facc0, 0xc42001ad20)
        /home/dhill/.go/src/github.com/companyzero/zkc/zkclient/msg.go:173 +0x351
created by main.(*ZKC).scheduler
        /home/dhill/.go/src/github.com/companyzero/zkc/zkclient/msg.go:116 +0x3d8

**Comment by marcopeereboom** [comment]
Fixed in #100
