### ISSUE TITLE
active window taken

### ISSUE THREAD

**Issue by dajohi** [companyzero/zkc#86]
The active window changes when invited to a GC with unknown users to a window with one of the unknown users.

12:34:58 <dhill> 12:27:09 handleGroupInvite: FindNick: marco (?): nick not found
12:35:14 <dhill> 12:27:09 To accept type /gc join zkc 661122
12:35:26 <dhill> 12:27:09 find failed: user not found
12:35:37 <dhill> 12:27:11 Client to Client Key Exchange complete:
12:35:39 <dhill> ...
12:35:50 <dhill> 12:27:11 conversation started [2]: marco aRployWKILKYEJzBBOK9kUKN7uQsxPWUOFBYWbaXKzQ=
12:36:20 <dhill> so when i was invited to a group chat, because i didn't know Marco at the time, it popped up a chat window for him and made it my active window

**Comment by marcopeereboom** [comment]
Fixed in #100
